
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony
    environment:
      - APP_ENV=dev
    networks:
      - symfony

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - symfony

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - symfony
    depends_on:
      - php
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  symfony: